In [28]:
import numpy as np

y = np.ones((10,2))
y

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
y[-1].reshape((2,))

array([1., 1.])

In [34]:
Y= np.zeros((2,2))
Y[1,:]=y[-1].reshape((1,2))
Y

array([[0., 0.],
       [1., 1.]])

In [38]:
init_state = np.zeros((2,1))
init_state[0] = 2
init_state

array([[2.],
       [0.]])

In [36]:
A = []
for _ in range(10):
    A.append(y[-1])

np.array(A)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [47]:
Pi = {}
Pi['U'] = {}

c = np.array([1,2])
Pi['U'][0] = np.ndarray.tolist(c)
Pi['U'][1] = 1

Pi

{'U': {0: [1, 2], 1: 1}}

In [53]:
u_t = np.array([0]).reshape(1,1)
u_t[0]

array([0])

In [60]:
class ParentClass:
    def sys_id(self, x_t, u_t):
        print("Parent sys_id method")
        print(f"x_t: {x_t}, u_t: {u_t}")

class ChildClass(ParentClass):
    def sys_id(self, x_t, u_t):
        print("Child sys_id method")
        print(f"x_t: {x_t}, u_t: {u_t}")

# Usage
parent_instance = ParentClass()
child_instance = ChildClass()

parent_instance.sys_id(1, 2)  # Works
child_instance.sys_id(1, 2)   # Works


Parent sys_id method
x_t: 1, u_t: 2
Child sys_id method
x_t: 1, u_t: 2


In [59]:
class ParentClass:
    def sys_id(self, x_t, u_t):
        print("Parent sys_id method")
        print(f"x_t: {x_t}, u_t: {u_t}")

class ChildClass(ParentClass):
    def sys_id(self, u_nom):
        print("Child sys_id method")
        print(f"u_nom: {u_nom}")

# Usage
parent_instance = ParentClass()
child_instance = ChildClass()

parent_instance.sys_id(1, 2)  # Works
child_instance.sys_id(1)      # Works differently


Parent sys_id method
x_t: 1, u_t: 2
Child sys_id method
u_nom: 1
